const prompts = {
  easy: {
    truths: ["What's your favorite cartoon as a kid?",
        "Have you ever cheated in a game?",
        "Do you talk in your sleep?",
        "What was your childhood nickname?",
        "Have you ever pretended to be sick?",
        "What's your most-used emoji?",
        "Do you sing in the shower?",
        "Have you ever stolen something small?",
        "Do you believe in ghosts?",
        "What’s your guilty pleasure show?",
        "Have you ever danced alone in your room?",
        "What’s the silliest thing you’re scared of?",
        "What's your go-to snack at 2AM?",
        "Have you ever laughed so hard you cried?",
        "What's your weirdest food combo?",
        "Ever told a lie to avoid homework?",
        "What's your favorite smell?",
        "Do you still sleep with a soft toy?",
        "What color would your lightsaber be?",
        "Who was your childhood crush?",
        "What animal would you want as a pet?",
        "Have you ever blamed a sibling for something you did?",
        "Do you sleep with the door open or closed?",
        "What's your most-used app?",
        "What's your weirdest dream?",
        "Do you believe in aliens?",
        "Would you survive a zombie apocalypse?",
        "What’s your most useless talent?",
        "What’s your secret superhero name?",
        "If you had a theme song, what would it be?"],
    dares: ["Act like a chicken for 15 seconds.",
        "Draw a mustache on your face with a pen.",
        "Sing the alphabet backwards.",
        "Text someone 'I know your secret.'",
        "Wear socks on your hands for 2 rounds.",
        "Make a funny face and keep it for 30 seconds.",
        "Speak without using the letter 'e' for 1 round.",
        "Take a silly selfie and share it in a group.",
        "Wrap yourself in a blanket and pretend to be a burrito.",
        "Spell your name using your body.",
        "Do 5 squats while saying your crush's name.",
        "Pretend to be a cat and meow until your next turn.",
        "Balance a spoon on your nose for 10 seconds.",
        "Talk in a baby voice until your next turn.",
        "Do a runway walk around the room.",
        "Let someone else style your hair.",
        "Say 3 things you like about yourself.",
        "Speak like a robot for 2 turns.",
        "Wear your shirt backward for the rest of the game.",
        "Draw a tattoo on your arm with a pen.",
        "Dance with no music for 20 seconds.",
        "Imitate a famous celebrity until someone guesses it.",
        "Write with your non-dominant hand for 1 round.",
        "Let another player send one emoji from your phone.",
        "Stand like a flamingo for a whole round.",
        "Make a toast like you're at a wedding.",
        "Try to juggle with 2+ random objects.",
        "Describe your dream home in dramatic style.",
        "Say a cheesy pickup line.",
        "Sing your favorite song like a metal singer."]
  },
  medium: {
    truths: ["Have you ever lied about your age?",
        "What's a secret you've never told anyone?",
        "What’s your biggest insecurity?",
        "Have you ever had a crush on a teacher?",
        "What’s the most awkward date you’ve been on?",
        "What's your most embarrassing wardrobe malfunction?",
        "Have you ever ghosted someone?",
        "What’s the biggest age gap you've dated?",
        "What’s something illegal you've done?",
        "What’s your worst habit?",
        "What's a weird turn-on you have?",
        "Have you ever been rejected badly?",
        "What do you Google that you’d be embarrassed about?",
        "What’s your weirdest fantasy?",
        "Have you ever been caught lying and denied it?",
        "What's your cringe childhood moment?",
        "Have you ever flirted just to get something?",
        "What’s something you’re ashamed you still enjoy?",
        "If you had 1 day left to live, what would you do?",
        "What’s something you pretend to like?",
        "Have you ever had a crush on a friend’s sibling?",
        "Have you ever cheated emotionally?",
        "What's the worst message you've sent by mistake?",
        "Would you date someone 10 years older?",
        "What's the worst lie you've told a parent?",
        "What's something dirty you've Googled?",
        "What’s the weirdest thing you've done alone?",
        "Have you had a crush on someone here?",
        "Have you ever flirted with a stranger in public?",
        "What’s your go-to excuse for avoiding plans?"],
    dares: [ "Send a text to your crush saying 'Hey 😳'",
        "Show the last photo in your gallery.",
        "Scroll your chat list and send a 👀 to someone random.",
        "Try to lick your elbow.",
        "Do an embarrassing dance in slow motion.",
        "Let someone go through your memes folder.",
        "Say 'I love you' to the person on your left.",
        "Speak in a British accent for 2 rounds.",
        "Draw something blindfolded and let others guess.",
        "Let someone write a message and post it to your story.",
        "Call someone and confess you stole their pen.",
        "Do your best impression of your favorite villain.",
        "Let someone dare you again (double dare!)",
        "Swap seats with someone and pretend to be them.",
        "Send a voice note saying 'I can’t stop thinking about you' to someone random.",
        "Do your best model catwalk while blowing kisses.",
        "Draw a heart on your face and keep it.",
        "Type a sentence with your nose.",
        "Read out your last 5 emojis and explain.",
        "Let someone choose a new nickname for you.",
        "Try to juggle 3 random objects.",
        "Post 'I love chaos' as a status for 10 mins.",
        "Hold an ice cube in your hand till it melts.",
        "Write ‘dare me’ on your forehead in pen.",
        "Imitate your last teacher for 20 seconds.",
        "Reveal your phone's screen time.",
        "Let someone DM your crush from your phone (you approve).",
        "Do the Macarena for 30 seconds.",
        "Try to rap about the person across from you.",
        "Let the group vote on your next dare."]
  },
  extreme: {
    truths: ["What’s the most adventurous thing you’ve done in bed?",
        "Describe your favorite position—be honest.",
        "Ever had a one-night stand? How was it?",
        "What’s your wildest hookup story?",
        "What's something you’ve done that you'd never tell your parents?",
        "Biggest turn-on no one expects?",
        "Have you ever had a spicy dream about someone in this room?",
        "Most public place you've done something NSFW?",
        "Have you ever faked it?",
        "Ever sent a risky pic?",
        "Do you like being dominant or submissive?",
        "Have you tried toys? Which ones?",
        "Describe your ideal dirty weekend.",
        "Ever been walked in on during something private?",
        "What's the weirdest NSFW thing you've searched for?",
        "Have you ever used dating apps just for hookups?",
        "Ever made out with someone of the same gender?",
        "Rate yourself as a lover from 1–10.",
        "Do you have a fantasy involving someone here?",
        "Ever sent a pic you regretted?",
        "Spit or swallow?",
        "Lights on or off?",
        "Do you enjoy being choked / choking?",
        "Weirdest kink you’ve considered but never tried?",
        "Have you ever roleplayed? What was it?",
        "Describe your last sext.",
        "Do you enjoy rough or soft?",
        "Have you ever recorded yourself?",
        "How long do you last?",
        "Describe your dirtiest fantasy in 5 words."],
    dares: ["Send a 😈 to your ex or crush.",
        "Lick your lips slowly while making eye contact with someone.",
        "Let someone check your hidden photo album (you can veto once).",
        "Fake moan loud enough for neighbors to hear.",
        "Do a sensual dance for 20 seconds.",
        "Whisper something dirty to the person next to you.",
        "Let someone send a 'you up?' text from your phone.",
        "Act out a fake orgasm. Max drama.",
        "Read your last NSFW message out loud.",
        "Let someone pick a contact for you to flirt-text.",
        "Show a pic you've never posted publicly.",
        "Remove one piece of clothing (safe zones only).",
        "Let the group vote on a person to give you a lap dance (or fake it).",
        "Let someone write something spicy on your stomach in pen.",
        "Call your crush and say 'I can’t stop thinking about you last night.'",
        "Let someone blindfold you and make you guess 3 items by touch.",
        "Do a body shot with imaginary drink.",
        "Open your last private browser tab and read its title.",
        "Twerk for 15 seconds. Full effort.",
        "Text someone 'You, me, tonight?' and screenshot their reply.",
        "Let someone send an audio of you saying 'I want you' seductively.",
        "Seductively eat something in the room.",
        "Let someone write 'property of ___' on your arm.",
        "Describe your last kiss in full detail.",
        "Flash a naughty smile at someone you’d sleep with.",
        "Pick someone to share a secret NSFW fantasy with (whisper only).",
        "Let someone ask you 1 uncensored question. You must answer.",
        "Give a lap pillow to someone for 1 round.",
        "Draw a temporary hickey on your neck.",
        "Whisper your safe word to someone and make eye contact."]
  }
};
